apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: graceful-app-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-6-grace-ardho-buildah
    - name: image-repo
      value: quay.io/ardho/graceful-app
  pipelineRef:
    name: expressjs
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce