apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/ardho/graceful-app
  newTag: 965364ce4ced48d3b2307947626ec3e37497c48d
commonLabels:
  app: graceful-app
  app.kubernetes.io/instance: graceful-app
  app.kubernetes.io/name: graceful-app
commonAnnotations:
  app.openshift.io/runtime: js
  app.openshift.io/vcs-ref: 965364ce4ced48d3b2307947626ec3e37497c48d
  app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-6-grace-ardho-buildah
