---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: graceful-app-pipeline-
      spec:
        pipelineRef:
          name: expressjs
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: graceful-app
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/emea-6-grace-ardho-buildah
          - name: image-repo
            value: quay.io/ardho/graceful-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
